apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-stage
resources:
  - my-project-helmrelease.yaml
  - namespace.yaml
  - external-secrets.yaml

configMapGenerator:
  - name: my-project-stage-values
    files:
      - values.yaml
    envs:
      - example.env
    literals:
      - FRUIT=apple

secretGenerator:
  - name: my-project-stage-secret
    files:
      - values.yaml
    literals:
      - FRUIT=apple
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
