apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-preview
resources:
  - preview.yaml
  - resourceinput.yaml
  - resourceset.yaml

generatorOptions:
  disableNameSuffixHash: true
