apiVersion: v1
entries:
  hello-world:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-25T17:21:16.628193+02:00"
    description: A Helm chart for Kubernetes
    digest: 996b1f00f6ccd832e2b6e7e474e8baa4902385ae16bf7a6f516f13fdf897a0c6
    name: hello-world
    type: application
    urls:
    - https://raw.githubusercontent.com/seekin4u/hetzner-kuber/main/charts/hello-world-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-25T17:21:16.627312+02:00"
