apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - my-project-helmrelease.yaml

configMapGenerator:
  - name: my-project-dev-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
