replicaCount: 1
environment: "dev"
logLevel: "debug"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: static.98.13.98.91.clients.your-server.de
  path: /dev/

serviceAccount:
  create: true
  annotations: {}
  name: ""

nameOverride: ""
fullnameOverride: my-project-dev-hello-world